//
// Checker for test-bannertopdf-unicode.sh: inspect the PDF generated by
// cfFilterBannerToPDF() for mixed ASCII and Unicode job information.
//
// Copyright © 2026 by OpenPrinting
//
// Licensed under Apache License v2.0.  See the file "LICENSE" for more
// information.
//

#include <pdfio.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>


static pdfio_dict_t *
get_dict(pdfio_dict_t *dict, const char *key)
{
  pdfio_obj_t *obj;

  if (pdfioDictGetType(dict, key) == PDFIO_VALTYPE_DICT)
    return pdfioDictGetDict(dict, key);

  if (pdfioDictGetType(dict, key) == PDFIO_VALTYPE_INDIRECT &&
      (obj = pdfioDictGetObj(dict, key)) != NULL)
    return pdfioObjGetDict(obj);

  return NULL;
}


static int
has_embedded_font(pdfio_dict_t *font)
{
  pdfio_array_t *descendants;
  pdfio_obj_t *descendant;
  pdfio_dict_t *descendant_dict, *descriptor;

  if ((descendants = pdfioDictGetArray(font, "DescendantFonts")) == NULL ||
      (descendant = pdfioArrayGetObj(descendants, 0)) == NULL ||
      (descendant_dict = pdfioObjGetDict(descendant)) == NULL ||
      (descriptor = get_dict(descendant_dict, "FontDescriptor")) == NULL)
    return 0;

  return pdfioDictGetObj(descriptor, "FontFile") != NULL ||
         pdfioDictGetObj(descriptor, "FontFile2") != NULL ||
         pdfioDictGetObj(descriptor, "FontFile3") != NULL;
}


static char *
read_page_streams(pdfio_obj_t *page)
{
  char *contents = NULL;
  size_t alloc = 0, length = 0, i, count;

  count = pdfioPageGetNumStreams(page);
  for (i = 0; i < count; i ++)
  {
    pdfio_stream_t *stream;
    char buffer[4096];
    ssize_t bytes;

    if ((stream = pdfioPageOpenStream(page, i, true)) == NULL)
    {
      free(contents);
      return NULL;
    }

    while ((bytes = pdfioStreamRead(stream, buffer, sizeof(buffer))) > 0)
    {
      size_t needed = length + (size_t)bytes + 1;

      if (needed > alloc)
      {
        char *temp;

        alloc = needed + 4095;
        if ((temp = realloc(contents, alloc)) == NULL)
        {
          free(contents);
          pdfioStreamClose(stream);
          return NULL;
        }
        contents = temp;
      }

      memcpy(contents + length, buffer, (size_t)bytes);
      length += (size_t)bytes;
    }

    pdfioStreamClose(stream);
  }

  if (!contents)
    return NULL;

  contents[length] = '\0';
  return contents;
}


int
main(int argc, char *argv[])
{
  pdfio_file_t *pdf;
  pdfio_obj_t *page;
  pdfio_dict_t *resources, *fonts, *unicode_font, *xobjects;
  char *contents;
  int status = 1;

  if (argc != 2)
  {
    fputs("Usage: test-bannertopdf-unicode OUTPUT.pdf\n", stderr);
    return 1;
  }

  if ((pdf = pdfioFileOpen(argv[1], NULL, NULL, NULL, NULL)) == NULL)
  {
    fprintf(stderr, "Unable to open \"%s\".\n", argv[1]);
    return 1;
  }

  if (pdfioFileGetNumPages(pdf) != 1)
  {
    fprintf(stderr, "Expected 1 output page, got %u.\n",
            (unsigned)pdfioFileGetNumPages(pdf));
    goto done;
  }

  page = pdfioFileGetPage(pdf, 0);
  if ((resources = get_dict(pdfioObjGetDict(page), "Resources")) == NULL ||
      (fonts = get_dict(resources, "Font")) == NULL)
  {
    fputs("Output page has no font resources.\n", stderr);
    goto done;
  }

  if ((xobjects = get_dict(resources, "XObject")) == NULL ||
      pdfioDictGetObj(xobjects, "x6") == NULL ||
      pdfioDictGetObj(xobjects, "x7") == NULL ||
      pdfioDictGetObj(xobjects, "x8") == NULL)
  {
    fputs("Template image resources were not preserved.\n", stderr);
    goto done;
  }

  if (get_dict(fonts, "bannertopdf-font") == NULL)
  {
    fputs("Courier banner font resource is missing.\n", stderr);
    goto done;
  }

  if ((unicode_font = get_dict(fonts, "bannertopdf-unicode-0")) == NULL)
  {
    fputs("Unicode banner font resource is missing.\n", stderr);
    goto done;
  }

  if (!pdfioDictGetName(unicode_font, "Subtype") ||
      strcmp(pdfioDictGetName(unicode_font, "Subtype"), "Type0"))
  {
    fputs("Unicode banner font is not a Type0 font.\n", stderr);
    goto done;
  }

  if (pdfioDictGetObj(unicode_font, "ToUnicode") == NULL)
  {
    fputs("Unicode banner font has no ToUnicode map.\n", stderr);
    goto done;
  }

  if (!has_embedded_font(unicode_font))
  {
    fputs("Unicode banner font is not embedded.\n", stderr);
    goto done;
  }

  if ((contents = read_page_streams(page)) == NULL)
  {
    fputs("Unable to read page content streams.\n", stderr);
    goto done;
  }

  if (!strstr(contents, "/bannertopdf-unicode-0 14 Tf") ||
      !strstr(contents, "<00E9> Tj"))
  {
    fputs("Unicode text was not emitted with the embedded font.\n", stderr);
    free(contents);
    goto done;
  }

  if (!strstr(contents, "/x6 Do") ||
      !strstr(contents, "/x7 Do") ||
      !strstr(contents, "/x8 Do"))
  {
    fputs("Template image drawing commands were not preserved.\n", stderr);
    free(contents);
    goto done;
  }

  if (!strstr(contents, "Office \\(Floor 2\\) \\\\ Queue"))
  {
    fputs("ASCII PDF literal string escaping is incorrect.\n", stderr);
    free(contents);
    goto done;
  }

  free(contents);
  puts("Unicode font embedding and banner content checks passed.");
  status = 0;

 done:
  pdfioFileClose(pdf);
  return status;
}
