name: Build and Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-linux-run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Show Ubuntu Version
        run: cat /etc/os-release | grep PRETTY_NAME | awk -F '=' '{print $2}'

      - name: Update Build Environment
        run: sudo apt-get update --fix-missing -y && sudo apt-get upgrade --fix-missing -y

      - name: Install Prerequisites
        run: |
          sudo apt-get install -y \
            avahi-daemon \
            libavahi-client-dev \
            libssl-dev \
            libpam-dev \
            libusb-1.0-0-dev \
            zlib1g-dev \
            autotools-dev \
            autopoint \
            cmake \
            libtool \
            pkg-config \
            libcups2-dev \
            libexif-dev \
            liblcms2-dev \
            libfontconfig1-dev \
            libfreetype6-dev \
            build-essential \
            qtbase5-dev \
            qtchooser \
            libcairo2-dev \
            libboost-system-dev \
            libboost-thread-dev \
            libboost-program-options-dev \
            libboost-test-dev \
            libopenjp2-7-dev \
            liblcms2-dev \
            libjpeg-dev

      - name: Install libqpdf > 11.0.0
        run: |
          wget https://sourceforge.net/projects/qpdf/files/qpdf/11.6.3/qpdf-11.6.3.tar.gz
          tar -xzf qpdf-11.6.3.tar.gz
          cd qpdf-11.6.3
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=/usr \
                -DCMAKE_BUILD_TYPE=Release \
                -DBUILD_STATIC_LIBS=OFF \
                -DCMAKE_INSTALL_DOCDIR=/usr/share/doc/qpdf-11.6.3 \
                ..
          make
          sudo make install

      - name: Install libpdfio > 1.3.0
        run: |
          wget https://github.com/michaelrsweet/pdfio/releases/download/v1.3.1/pdfio-1.3.1.tar.gz
          tar -xzf pdfio-1.3.1.tar.gz
          cd pdfio-1.3.1
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=/usr \
                -DCMAKE_BUILD_TYPE=Release \
                -DBUILD_STATIC_LIBS=OFF \
                -DCMAKE_INSTALL_DOCDIR=/usr/share/doc/pdfio-1.3.1 \
                ..
          make
          sudo make install

      - name: Install poppler and mupdf
        run: |
          sudo apt-get install -y \
            libpoppler-cpp-dev \
            libpython3-dev \
            libdbus-1-dev \
            mupdf-tools

      - name: Install Ghostscript
        run: sudo apt-get install -y ghostscript

      - name: Configure
        env:
          CC: /usr/bin/gcc
        run: ./autogen.sh && ./configure --enable-debug

      - name: Build
        run: make

      - name: Run Tests
        run: make check || (test -f test/error_log* && cat test/error_log*)
